### ISSUE TITLE
Why use GH wiki when the site exists? If this is a todo, will the wiki be a clone [of the site]?

### ISSUE THREAD

**Issue by insyri** [RoManager-org/romanager-oss#7]
Talking about this specifically.

https://github.com/RoManager-org/romanager-oss/blame/main/README.md#L8
> ~~Instructions to start your own instance of RoManager are in the wiki: https://github.com/RoManager-org/romanager-oss/wiki.~~ (not yet complete)

**Comment by jaydensar** [comment]
I was gonna do this to separate the public-facing version of RoManager from the self-hosted version as to not confuse users, but it's probably a better idea to create a new area on the site for self-hosted docs, and probably what I'm going to do now.
